/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quiz1;

import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class kopijaya extends javax.swing.JFrame {

    /**
     * Creates new form kopijaya
     */
    public kopijaya() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        combokopi = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtorder = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        kopi = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();
        jumlah = new javax.swing.JLabel();
        bayar = new javax.swing.JLabel();
        btnclear = new javax.swing.JButton();
        btnfinish = new javax.swing.JButton();
        btnout = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(103, 57, 0));
        jLabel1.setText(" WELCOME TO");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(103, 57, 0));
        jLabel2.setText("STARS COFFEE");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(103, 57, 0));
        jLabel3.setText("CONTACT : 0899-4433-6776");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(103, 57, 0));
        jLabel4.setText("EMAIL : STARSCOFFE@GMAIL.COM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 633, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(103, 57, 0));
        jLabel5.setText("COFFEE BEAN");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 48, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(103, 57, 0));
        jLabel6.setText(":");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 48, -1, -1));

        combokopi.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        combokopi.setForeground(new java.awt.Color(103, 57, 0));
        combokopi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ARABICA COFFEE", "ROBUSTA COFFEE", "LIBERIAN COFFEE", "EXCELSA COFFEE" }));
        jPanel2.add(combokopi, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 45, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(103, 57, 0));
        jLabel7.setText("ORDER QUANTITY");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 98, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(103, 57, 0));
        jLabel8.setText(":");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 98, -1, -1));

        txtorder.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        txtorder.setForeground(new java.awt.Color(103, 57, 0));
        jPanel2.add(txtorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 95, 200, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(103, 57, 0));
        jLabel9.setText("COFFEE");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 145, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(103, 57, 0));
        jLabel10.setText(":");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 145, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(103, 57, 0));
        jLabel11.setText("PRICE");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 189, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(103, 57, 0));
        jLabel12.setText(":");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 189, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(103, 57, 0));
        jLabel13.setText("ITEM(S) AMOUNT");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 233, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(103, 57, 0));
        jLabel14.setText(":");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 233, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(103, 57, 0));
        jLabel15.setText("--------------------------------------------------------------------------------");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 277, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(103, 57, 0));
        jLabel16.setText("TOTAL PRICE");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 321, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(103, 57, 0));
        jLabel17.setText(":");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 321, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(103, 57, 0));
        jLabel18.setText("THANK YOU FOR YOUR ORDER");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 474, -1, -1));

        kopi.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        kopi.setForeground(new java.awt.Color(103, 57, 0));
        jPanel2.add(kopi, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 145, 211, -1));

        harga.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        harga.setForeground(new java.awt.Color(103, 57, 0));
        jPanel2.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 189, 211, -1));

        jumlah.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jumlah.setForeground(new java.awt.Color(103, 57, 0));
        jPanel2.add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 233, 211, -1));

        bayar.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        bayar.setForeground(new java.awt.Color(103, 57, 0));
        jPanel2.add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 321, 209, -1));

        btnclear.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnclear.setForeground(new java.awt.Color(103, 57, 0));
        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel2.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 381, -1, 42));

        btnfinish.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnfinish.setForeground(new java.awt.Color(103, 57, 0));
        btnfinish.setText("FINISH");
        btnfinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfinishActionPerformed(evt);
            }
        });
        jPanel2.add(btnfinish, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 381, -1, 42));

        btnout.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnout.setForeground(new java.awt.Color(103, 57, 0));
        btnout.setText("SIGN OUT");
        btnout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnout, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 381, -1, 42));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\1.png")); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnfinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfinishActionPerformed
        // TODO add your handling code here:
         String fjmlpesanan = txtorder.getText();
         
         String selectedOptionskopi = (String) combokopi.getSelectedItem();
         if (combokopi.getSelectedIndex() == 0) {
        // Logika jika indeks 0 (item pertama) dipilih
        kopi.setText(""+selectedOptionskopi);
        int ind0=45000;
        jumlah.setText(""+fjmlpesanan);
        harga.setText(""+ind0);
        int total=ind0*Integer.parseInt(fjmlpesanan);
        Integer.valueOf(total);
        bayar.setText(""+total);
         }
         if (combokopi.getSelectedIndex() == 1) {
        // Logika jika indeks 0 (item pertama) dipilih
        kopi.setText(""+selectedOptionskopi);
        int ind1=40000;
        jumlah.setText(""+fjmlpesanan);
        harga.setText(""+ind1);
        int total=ind1*Integer.parseInt(fjmlpesanan);
        Integer.valueOf(total);
          bayar.setText(""+total);
         }
         if (combokopi.getSelectedIndex() == 2) {
        // Logika jika indeks 0 (item pertama) dipilih
        kopi.setText(""+selectedOptionskopi);
        int ind2=50000;
        jumlah.setText(""+fjmlpesanan);
        harga.setText(""+ind2);
        int total=ind2*Integer.parseInt(fjmlpesanan);
        Integer.valueOf(total);
          bayar.setText(""+total);
         }
         if (combokopi.getSelectedIndex() == 3) {
        // Logika jika indeks 0 (item pertama) dipilih
        kopi.setText(""+selectedOptionskopi);
        
        int ind3=35000;
        harga.setText(""+ind3);
        jumlah.setText(""+fjmlpesanan);
        int total=ind3*Integer.parseInt(fjmlpesanan);
        Integer.valueOf(total);
          bayar.setText(""+total);}
         
        
    }//GEN-LAST:event_btnfinishActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
         txtorder.setText("");
 combokopi.setSelectedIndex(0); // Mengatur ulang prodi ke indeks pertama
 kopi.setText("");
 bayar.setText("");
 harga.setText("");
 jumlah.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoutActionPerformed
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(
        this,
        "are you sure?",
        "Konfirmasi Keluar",
        JOptionPane.YES_NO_OPTION
    );

    if (confirmed == JOptionPane.YES_OPTION) {
        // Menghentikan program secara normal
        System.exit(0);
    }
    }//GEN-LAST:event_btnoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kopijaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kopijaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kopijaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kopijaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kopijaya().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bayar;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnfinish;
    private javax.swing.JButton btnout;
    private javax.swing.JComboBox<String> combokopi;
    private javax.swing.JLabel harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jumlah;
    private javax.swing.JLabel kopi;
    private javax.swing.JTextField txtorder;
    // End of variables declaration//GEN-END:variables
}
